name: github-graphql
channels:
  - conda-forge
dependencies:
  - aiohttp >=3.7.1,<3.8.0
  - python 3.8
  - python-dotenv
  - jupyterlab
  - pip
  - requests >=2.23,<3
  - websockets >=8.1,<9
  - pip:
    - gql==3.0.0a5 
